name: Build RSDKv5

on: workflow_dispatch

# each artifact is like 15MB so we'll start by only doing it manually
# on:
#   push:
#     branches:
#       - master

# TODO: readd with: submodules: recursive once we can

jobs:
  v5-windows:
    runs-on: windows-2022
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: vcpkg build
        uses: johnwason/vcpkg-action@v6
        id: vcpkg
        with:
          pkgs: libtheora libogg
          triplet: x64-windows-static
          token: ${{ github.token }}
          github-binarycache: true
      - name: install cmake
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
      - name: Use cmake
        run: |
          cmake -B build -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}\vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static
          cmake --build build --config release

      - name: Move artifacts
        run: |
          mkdir artifacts
          mv ./build ./artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v1.0.0
        with:
          name: v5-windows
          path: artifacts
