name: Build RSDKv5u
on:
  workflow_dispatch

jobs:
  mania:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      - name: Build RSDKv5u
        run: |
          msbuild RSDKv5U.sln -target:RSDKv5U-dx9 /p:Configuration=Release /p:Platform=x64 /p:ForceImportBeforeCppTargets="$env:GITHUB_WORKSPACE/props/winactions.props"
      - name: Move artifacts
        run: |
          mkdir artifacts
          move ./build/Win32/Release/* ./artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v1.0.0
        with:
          name: v5u-windows
          path: artifacts
