name: Build RSDKv5U
on:
  workflow_dispatch

jobs:
  rsdkv5u:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Get dependencies
        uses: |
          sudo apt-get update
          sudo apt install build-essential libglew-dev libglfw3-dev libtheora-dev zlib1g-dev libsdl2-dev
      - name: Build RSDKv5U
        uses: |
          make RSDK_ONLY=1 RSDK_REVISION=3
      - name: Upload artifacts
        uses: actions/upload-artifact@v1.0.0
        with:
          name: rsdkv5u
          path: bin/Linux
