name: Build RSDKv5U
on:
  workflow_dispatch

jobs:
  rsdkv5u:
    runs-on: windows-2022
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW32
          update: true
          install: pkg-config mingw-w64-SDL2 mingw-w64-i686-libogg mingw-w64-i686-libtheora
      - name: Build rsdkv5u
        run: |
          msbuild RSDKv5U.sln -target:RSDKv5U-dx9 /p:Configuration=Release /p:Platform=x86 /p:ForceImportBeforeCppTargets="$env:GITHUB_WORKSPACE/props/winactions.props"
      - name: Move artifacts
        run: |
          mkdir artifacts
          move ./build/x86/Release/DX9/* ./artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v1.0.0
        with:
          name: rsdkv5u
          path: artifacts
